# Generated by Django 4.0.5 on 2022-06-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
